env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: gkup-core-build
    main: ./cmd/gkup-core
    binary: gkup-core
    ldflags: -X github.com/Miguel-Dorta/gkup-core/internal.Version={{.Version}}
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

archives:
  - id: gkup-core-archive
    builds:
      - gkup-core-build
    format: binary
